### ISSUE TITLE
Weird graph

### ISSUE THREAD

**Issue by victorgabr** [ThePrimeagen/vim-conf#2]
I am getting this result using the CSV you pushed.

![image](https://user-images.githubusercontent.com/6777517/90924999-86053100-e3be-11ea-95df-7f29cbf00a85.png)

**Comment by ThePrimeagen** [comment]
@victorgabr are you able to send me your csv?  I wants the data!

**Comment by ThePrimeagen** [comment]
Discord: https://discord.gg/3ujcVMe

**Comment by victorgabr** [comment]
I have submitted a PR with sweet sweet graphs.
